/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.com.unir.farmaciaunir.view;

import co.com.unir.farmaciaunir.controller.GenerarPedido;
import co.com.unir.farmaciaunir.model.Pedido;
import java.awt.Component;
import java.awt.Container;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Enumeration;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author ivanc
 */
public class RegistroPedidoFrame extends javax.swing.JFrame {

    public Pedido pedido;
    private ButtonGroup bg;
    private final String SUCURSAL_PRINCIPAL = "Principal";
    private final String SUCURSAL_SECUNDARIA = "Secundaria";

    /**
     * Creates new form DisplayFrame
     */
    public RegistroPedidoFrame() {
        if (pedido == null) {
            pedido = new Pedido();
        }
        this.bg = new ButtonGroup();
        initComponents();
        // Agrega al ComboBox los items a escoger
        List<String> tiposMedicamentos = new ArrayList<>(Arrays.asList("Analgésico", "Analéptico", "Anestésico",
                "Antiácido", "Antidepresivo", "Antibióticos")).stream().sorted().collect(Collectors.toList());
        tiposMedicamentos.forEach(item -> tipoMedicamentoComboBox.addItem(item));
        // Agrega el button group los radio button para que se eliga solamente uno
        bg.add(distriCemefar);
        bg.add(distriEmpsephar);
        bg.add(distriCofarma);

        this.registrarPedido.setText(this.registrarPedido.getText().toUpperCase());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        medicamento = new javax.swing.JTextField();
        medicamentoLabel = new javax.swing.JLabel();
        tipoMedicamentoLabel = new javax.swing.JLabel();
        cantidadLabel = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        distribuidorLabel = new javax.swing.JLabel();
        distriCofarma = new javax.swing.JRadioButton();
        distriEmpsephar = new javax.swing.JRadioButton();
        distriCemefar = new javax.swing.JRadioButton();
        sucursalLabel = new javax.swing.JLabel();
        sucursalPrincipal = new javax.swing.JCheckBox();
        sucursalSecundaria = new javax.swing.JCheckBox();
        borrarBtn = new javax.swing.JButton();
        confirmarBtn = new javax.swing.JButton();
        registrarPedido = new javax.swing.JLabel();
        tipoMedicamentoComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        logoUnir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 108, 187));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setName(""); // NOI18N

        medicamento.setForeground(new java.awt.Color(0, 108, 187));
        medicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                medicamentoKeyTyped(evt);
            }
        });

        medicamentoLabel.setForeground(new java.awt.Color(255, 255, 255));
        medicamentoLabel.setText("Nombre del medicamento");

        tipoMedicamentoLabel.setForeground(new java.awt.Color(255, 255, 255));
        tipoMedicamentoLabel.setText("Tipo de medicamento");

        cantidadLabel.setForeground(new java.awt.Color(255, 255, 255));
        cantidadLabel.setText("Cantidad requerida");

        cantidad.setForeground(new java.awt.Color(0, 108, 187));
        cantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadKeyTyped(evt);
            }
        });

        distribuidorLabel.setForeground(new java.awt.Color(255, 255, 255));
        distribuidorLabel.setText("Nombre del distribuidor farmacéutico");

        distriCofarma.setBackground(new java.awt.Color(0, 108, 187));
        distriCofarma.setForeground(new java.awt.Color(255, 255, 255));
        distriCofarma.setLabel("Cofarma");

        distriEmpsephar.setBackground(new java.awt.Color(0, 108, 187));
        distriEmpsephar.setForeground(new java.awt.Color(255, 255, 255));
        distriEmpsephar.setLabel("Empsephar");

        distriCemefar.setBackground(new java.awt.Color(0, 108, 187));
        distriCemefar.setForeground(new java.awt.Color(255, 255, 255));
        distriCemefar.setLabel("Cemefar");

        sucursalLabel.setForeground(new java.awt.Color(255, 255, 255));
        sucursalLabel.setText("Sucursal");

        sucursalPrincipal.setBackground(new java.awt.Color(0, 108, 187));
        sucursalPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        sucursalPrincipal.setText("Principal");
        sucursalPrincipal.setActionCommand("");

        sucursalSecundaria.setBackground(new java.awt.Color(0, 108, 187));
        sucursalSecundaria.setForeground(new java.awt.Color(255, 255, 255));
        sucursalSecundaria.setText("Secundaria");

        borrarBtn.setBackground(new java.awt.Color(255, 255, 255));
        borrarBtn.setForeground(new java.awt.Color(0, 108, 187));
        borrarBtn.setText("Borrar");
        borrarBtn.setMaximumSize(new java.awt.Dimension(84, 22));
        borrarBtn.setMinimumSize(new java.awt.Dimension(84, 22));
        borrarBtn.setPreferredSize(new java.awt.Dimension(84, 22));
        borrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBtnActionPerformed(evt);
            }
        });

        confirmarBtn.setBackground(new java.awt.Color(255, 255, 255));
        confirmarBtn.setForeground(new java.awt.Color(0, 108, 187));
        confirmarBtn.setText("Confirmar");
        confirmarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarBtnActionPerformed(evt);
            }
        });

        registrarPedido.setBackground(new java.awt.Color(0, 102, 255));
        registrarPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registrarPedido.setForeground(new java.awt.Color(255, 255, 255));
        registrarPedido.setText("Registrar pedido");

        tipoMedicamentoComboBox.setForeground(new java.awt.Color(0, 108, 187));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        logoUnir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unirPharmacy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(logoUnir, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(logoUnir, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sucursalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(distriCofarma)
                                .addGap(18, 18, 18)
                                .addComponent(distriEmpsephar)
                                .addGap(18, 18, 18)
                                .addComponent(distriCemefar))
                            .addComponent(distribuidorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoMedicamentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoMedicamentoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medicamentoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(registrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(borrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sucursalPrincipal)
                                .addGap(18, 18, 18)
                                .addComponent(sucursalSecundaria)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(medicamentoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tipoMedicamentoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoMedicamentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cantidadLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(distribuidorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distriCofarma)
                    .addComponent(distriEmpsephar)
                    .addComponent(distriCemefar))
                .addGap(18, 18, 18)
                .addComponent(sucursalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sucursalPrincipal)
                    .addComponent(sucursalSecundaria))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyTyped
        char validar = evt.getKeyChar();
        if (!Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_cantidadKeyTyped

    private void medicamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_medicamentoKeyTyped
        char validar = evt.getKeyChar();
        if (!(Character.isLetterOrDigit(validar) || Character.isWhitespace(validar))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_medicamentoKeyTyped

    private void borrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBtnActionPerformed
        resetComponents(this.getContentPane());
    }//GEN-LAST:event_borrarBtnActionPerformed

    private void confirmarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarBtnActionPerformed

        if (medicamento.getText().isBlank() || cantidad.getText().isBlank() || bg.getSelection() == null || (!sucursalPrincipal.isSelected() && !sucursalSecundaria.isSelected())) {
            JOptionPane.showMessageDialog(this, "Verifique el formulario, campos incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            List<String> sucursal = new ArrayList<>();
            if (sucursalPrincipal.isSelected()) {
                sucursal.add(SUCURSAL_PRINCIPAL);
            }
            if (sucursalSecundaria.isSelected()) {
                sucursal.add(SUCURSAL_SECUNDARIA);
            }
            this.pedido = new Pedido();
            pedido.setNombreMedicamento(medicamento.getText());
            pedido.setTipoMedicamento(tipoMedicamentoComboBox.getSelectedItem().toString());
            pedido.setCantidadMedicamento(Long.parseLong(cantidad.getText()));
            pedido.setSucursal(sucursal);
            for (Enumeration<AbstractButton> buttons = bg.getElements(); buttons.hasMoreElements();) {
                AbstractButton button = buttons.nextElement();
                if (button.isSelected()) {
                    pedido.setNombreDistribuidor(button.getText());
                }
            }
            GenerarPedido generarPedido = new GenerarPedido();
            generarPedido.crearPedido(pedido);
        }
    }//GEN-LAST:event_confirmarBtnActionPerformed

    private void resetComponents(Container container) {
        Component[] components = container.getComponents();
        for (Component component : components) {
            if (component instanceof JTextField) {
                ((JTextField) component).setText("");
            } else if (component instanceof JCheckBox) {
                ((JCheckBox) component).setSelected(false);
            } else if (component instanceof JRadioButton) {
                ((JRadioButton) component).setSelected(false);
                bg.clearSelection();
            } else if (component instanceof JComboBox) {
                ((JComboBox<?>) component).setSelectedIndex(0);
            } else if (component instanceof Container) {
                resetComponents((Container) component);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cantidad;
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JButton confirmarBtn;
    private javax.swing.JRadioButton distriCemefar;
    private javax.swing.JRadioButton distriCofarma;
    private javax.swing.JRadioButton distriEmpsephar;
    private javax.swing.JLabel distribuidorLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logoUnir;
    private javax.swing.JTextField medicamento;
    private javax.swing.JLabel medicamentoLabel;
    private javax.swing.JLabel registrarPedido;
    private javax.swing.JLabel sucursalLabel;
    private javax.swing.JCheckBox sucursalPrincipal;
    private javax.swing.JCheckBox sucursalSecundaria;
    private javax.swing.JComboBox<String> tipoMedicamentoComboBox;
    private javax.swing.JLabel tipoMedicamentoLabel;
    // End of variables declaration//GEN-END:variables
}
